### ISSUE TITLE
Exception during certificate parsing

### ISSUE THREAD

**Issue by pi-andrei** [eu-digital-green-certificates/dgca-verifier-service#23]
## Description
While trying to use dgca-verifier-service to download CSCA and UPLOAD certificates from the test dgc-gateway, we faced with an issue. While validating downloaded UPLOAD certificates, application throws an exception. See logs:

[log1.txt](https://github.com/eu-digital-green-certificates/dgca-verifier-service/files/6441045/log1.txt)

Issue happens because uploadCertificate variable in the checkUploadCertificate method equals to null. Hovewer, the root exception happens in the SignedCertificateMessageParser class during initialization on the line:

![image](https://user-images.githubusercontent.com/7721441/117441288-cf41e480-af3d-11eb-8d4d-1c8b4c60e62d.png)

After that line, it throws an exeption:
[log2.txt](https://github.com/eu-digital-green-certificates/dgca-verifier-service/files/6441085/log2.txt)

As an result uploadCertificate in the method checkUploadCertificate is null.

## Expected behaviour

dgca-verifier-service shall not fail during processing UPLOAD certificates.

## Steps to reproduce the issue

1. Configure application to run against the test dgc-gateway
2. Run the dgca-verifier-service application
2. Wait test certificates are downloaded
3. Check in the logs that certificate verification failed

## Technical details

- Host Machine OS: Ubuntu 20.04.2 LTS
- JDK 11.0.10
- Environment: test dgc-gateway

## Additional context

One suggestion: I suggest to improve dgc-lib to not throw NullPointerException, if one of the sertificate parsing fails using SignedCertificateMessageParser. Is it possible to skip such certificates?

**Comment by slaurenz** [comment]
Thanks for the report and your analysis. We will look for a solution.

**Comment by f11h** [comment]
Thanks for reporting this bug!
The bug is now fixed and the signatures should be correct. 
At the moment we still have invalid signatures on tst env because they need to be recreated.

The fix is in dgc-lib and it is fixed in version 0.4.2

Corresponding Bugs:
https://github.com/eu-digital-green-certificates/dgc-gateway/issues/57
https://github.com/eu-digital-green-certificates/dgc-lib/issues/24

**Comment by pi-andrei** [comment]
Using dgc-lib version 0.4.2, I'm still getting NPE:
```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	at eu.europa.ec.dgc.gateway.connector.DgcGatewayDownloadConnector.checkUploadCertificate(DgcGatewayDownloadConnector.java:219) ~[dgc-lib-0.4.2.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at eu.europa.ec.dgc.gateway.connector.DgcGatewayDownloadConnector.fetchTrustListAndVerifyByCscaAndUpload(DgcGatewayDownloadConnector.java:183) ~[dgc-lib-0.4.2.jar:na]
	at eu.europa.ec.dgc.gateway.connector.DgcGatewayDownloadConnector.updateIfRequired(DgcGatewayDownloadConnector.java:127) ~[dgc-lib-0.4.2.jar:na]
	at eu.europa.ec.dgc.gateway.connector.DgcGatewayDownloadConnector.getTrustedCertificates(DgcGatewayDownloadConnector.java:112) ~[dgc-lib-0.4.2.jar:na]
	at eu.europa.ec.dgc.verifier.service.SignerCertificateDownloadServiceImpl.downloadCertificates(SignerCertificateDownloadServiceImpl.java:54) ~[classes/:na]
	at eu.europa.ec.dgc.verifier.service.SignerCertificateDownloadServiceImpl$$FastClassBySpringCGLIB$$1e4ae2e5.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.5.jar:5.3.5]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.5.jar:5.3.5]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.5.jar:5.3.5]
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:73) ~[shedlock-core-4.23.0.jar:na]
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86) ~[shedlock-spring-4.23.0.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.5.jar:5.3.5]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.5.jar:5.3.5]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.5.jar:5.3.5]
	at eu.europa.ec.dgc.verifier.service.SignerCertificateDownloadServiceImpl$$EnhancerBySpringCGLIB$$9dac3c40.downloadCertificates(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.5.jar:5.3.5]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
But I found that there is parameter disable-upload-certificate-check which can be set to true to skip this logic. Will use that temporary.

Also, after a commit with BTP service implementation,  scheduler job is not started using the default profile (however using btp profile starts btp service job).

**Comment by f11h** [comment]
Sorry, these NPE are because of the broken signatures which are still present in TST environment.

In the meantime I've released version 0.4.3 of dgc-lib which catches these bad signatures. Please upgrade and try again.

**Comment by slaurenz** [comment]
The default profile should also be fixed  with the last PR. The scheduler should run again. 
Sorry for the inconvenience.

**Comment by pi-andrei** [comment]
Thanks, all good now, except broken signatures.

**Comment by f11h** [comment]
the broken signatures are "healing" in the meantime.
I will close this issue.
